//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpAuthentication130524.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public int id { get; set; }
        public int login_id { get; set; }
        public string role { get; set; }
    
        public virtual tblLogin tblLogin { get; set; }
    }
}
